# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"
# Fix line endings on Windows
init:
  - git config --global core.autocrlf input
  - git config --system core.longpaths true
environment:
  matrix:
    - nodejs_version: "10.18.1"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build:prod
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run the test
  - cmd: npm run lint --silent
  - cmd: npm run test-compile && npm run test-ci --silent

build: off
matrix:
  fast_finish: true
